/* Generated by AN DISI Unibo */ 
package it.unibo.sonarlorisdavide

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonarlorisdavide ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						emit("local_sonardata", "distance($D)" ) 
					}
					 transition(edgeName="t076",targetState="s0",cond=whenDispatch("sonardeactivate"))
					transition(edgeName="t077",targetState="s0",cond=whenDispatch("sonaractivate"))
				}	 
			}
		}
}
