/* Generated by AN DISI Unibo */ 
package it.unibo.coapdispatch

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Coapdispatch ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CoapObserverSupport(myself, "127.0.0.1","8096","ctxrobot","transporttrolley")
						CoapObserverSupport(myself, "127.0.0.1","8096","ctxrobot","basicrobotwrapper")
						CoapObserverSupport(myself, "127.0.0.1","8096","ctxrobot","pickupdropouthandler")
						CoapObserverSupport(myself, "127.0.0.1","8096","ctxrobot","mover")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
					transition(edgeName="t01",targetState="handleLed",cond=whenEvent("update_led"))
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								discardMessages = false
								forward("coapUpdate", "coapUpdate(RESOURCE,VALUE)" ,"transporttrolleystate" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
					transition(edgeName="t03",targetState="handleLed",cond=whenEvent("update_led"))
				}	 
				state("handleLed") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("update_led(LEDSTATE)"), Term.createTerm("update_led(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								discardMessages = false
								forward("update_led", "update_led(ARG)" ,"led" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
					transition(edgeName="t05",targetState="handleLed",cond=whenEvent("update_led"))
				}	 
			}
		}
}
