/* Generated by AN DISI Unibo */ 
package it.unibo.moveruturn

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Moveruturn ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		  lateinit var RES : String
				var ENDDIR : String? = null  
		return { //this:ActionBasciFsm
				state("wait") { //this:State
					action { //it:State
						discardMessages = true
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(wait,$ENDDIR)"  
						)
					}
					 transition(edgeName="t050",targetState="req_halt",cond=whenRequest("moveruturn"))
				}	 
				state("req_halt") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("moveruturn(CURRDIR)"), Term.createTerm("moveruturn(DIR)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ENDDIR = when(payloadArg(0)){
												"ACLK" -> "CLK"
												"CLK"  -> "ACLK"
												else -> {println("moveruturn | error: unknow direction"); ""}
											   }  
						}
						updateResourceRep( "moveruturn(req_halt,$ENDDIR)"  
						)
						request("cmdsync", "cmdsync(h)" ,"basicrobotwrapper" )  
					}
					 transition(edgeName="t051",targetState="chk_halt",cond=whenReply("cmdanswer"))
				}	 
				state("chk_halt") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(chk_halt,$ENDDIR)"  
						)
						if( checkMsgContent( Term.createTerm("cmdanswer(RESULT)"), Term.createTerm("cmdanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
						}
					}
					 transition( edgeName="goto",targetState="req_turn_1", cond=doswitchGuarded({ RES=="OK"  
					}) )
					transition( edgeName="goto",targetState="error", cond=doswitchGuarded({! ( RES=="OK"  
					) }) )
				}	 
				state("req_turn_1") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(req_turn_1,$ENDDIR)"  
						)
						request("cmdsync", "cmdsync(l)" ,"basicrobotwrapper" )  
					}
					 transition(edgeName="t052",targetState="chk_turn_1",cond=whenReply("cmdanswer"))
				}	 
				state("chk_turn_1") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(chk_turn_1,$ENDDIR)"  
						)
						if( checkMsgContent( Term.createTerm("cmdanswer(RESULT)"), Term.createTerm("cmdanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
						}
					}
					 transition( edgeName="goto",targetState="req_turn_2", cond=doswitchGuarded({ RES=="OK"  
					}) )
					transition( edgeName="goto",targetState="error", cond=doswitchGuarded({! ( RES=="OK"  
					) }) )
				}	 
				state("req_turn_2") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(req_turn_2,$ENDDIR)"  
						)
						request("cmdsync", "cmdsync(l)" ,"basicrobotwrapper" )  
					}
					 transition(edgeName="t053",targetState="chk_turn_2",cond=whenReply("cmdanswer"))
				}	 
				state("chk_turn_2") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(chk_turn_2,$ENDDIR)"  
						)
						if( checkMsgContent( Term.createTerm("cmdanswer(RESULT)"), Term.createTerm("cmdanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
						}
					}
					 transition( edgeName="goto",targetState="req_forward", cond=doswitchGuarded({ RES=="OK"  
					}) )
					transition( edgeName="goto",targetState="error", cond=doswitchGuarded({! ( RES=="OK"  
					) }) )
				}	 
				state("req_forward") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(req_forward,$ENDDIR)"  
						)
						request("cmdsync", "cmdsync(w)" ,"basicrobotwrapper" )  
					}
					 transition(edgeName="t054",targetState="chk_forward",cond=whenReply("cmdanswer"))
				}	 
				state("chk_forward") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(chk_forward,$ENDDIR)"  
						)
						if( checkMsgContent( Term.createTerm("cmdanswer(RESULT)"), Term.createTerm("cmdanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
						}
					}
					 transition( edgeName="goto",targetState="req_final_turn", cond=doswitchGuarded({ RES=="OK"  
					}) )
					transition( edgeName="goto",targetState="error", cond=doswitchGuarded({! ( RES=="OK"  
					) }) )
				}	 
				state("req_final_turn") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(req_final_turn,$ENDDIR)"  
						)
						if(  ENDDIR == "ACLK"  
						 ){request("cmdsync", "cmdsync(l)" ,"basicrobotwrapper" )  
						}
						else
						 {request("cmdsync", "cmdsync(r)" ,"basicrobotwrapper" )  
						 }
					}
					 transition(edgeName="t055",targetState="chk_final_turn",cond=whenReply("cmdanswer"))
				}	 
				state("chk_final_turn") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(chk_final_turn,$ENDDIR)"  
						)
						if( checkMsgContent( Term.createTerm("cmdanswer(RESULT)"), Term.createTerm("cmdanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
						}
					}
					 transition( edgeName="goto",targetState="reply", cond=doswitchGuarded({ RES=="OK"  
					}) )
					transition( edgeName="goto",targetState="error", cond=doswitchGuarded({! ( RES=="OK"  
					) }) )
				}	 
				state("reply") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						answer("moveruturn", "moveruturnanswer", "moveruturnanswer(OK)"   )  
						updateResourceRep( "moveruturn(reply,$ENDDIR)"  
						)
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("error") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "moveruturn(error,$ENDDIR)"  
						)
						answer("moveruturn", "moveruturnanswer", "moveruturnanswer(ERROR)"   )  
						println("moveruturn | ERROR STATE")
					}
				}	 
			}
		}
}
