/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
			var newState = ws.LedState.OFF	 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "led(initial,${newState})"  
						)
						println("led off")
					}
					 transition(edgeName="t00",targetState="handle_update",cond=whenEvent("update_led"))
				}	 
				state("handle_update") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("update_led(LEDSTATE)"), Term.createTerm("update_led(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 newState = ws.LedState.valueOf(payloadArg(0))  
						}
						updateResourceRep( "led(handle_update,${newState})"  
						)
					}
					 transition( edgeName="goto",targetState="off", cond=doswitchGuarded({ newState==ws.LedState.OFF  
					}) )
					transition( edgeName="goto",targetState="handle_update_switch_1", cond=doswitchGuarded({! ( newState==ws.LedState.OFF  
					) }) )
				}	 
				state("handle_update_switch_1") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="on", cond=doswitchGuarded({ newState==ws.LedState.ON  
					}) )
					transition( edgeName="goto",targetState="handle_update_switch_2", cond=doswitchGuarded({! ( newState==ws.LedState.ON  
					) }) )
				}	 
				state("handle_update_switch_2") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="blink_on", cond=doswitchGuarded({ newState==ws.LedState.BLINK  
					}) )
					transition( edgeName="goto",targetState="handle_update", cond=doswitchGuarded({! ( newState==ws.LedState.BLINK  
					) }) )
				}	 
				state("off") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "led(off,${newState})"  
						)
						println("led off")
					}
					 transition(edgeName="t01",targetState="handle_update",cond=whenEvent("update_led"))
				}	 
				state("on") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "led(on,${newState})"  
						)
						println("led on")
					}
					 transition(edgeName="t02",targetState="handle_update",cond=whenEvent("update_led"))
				}	 
				state("blink_on") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "led(blink_on,${newState})"  
						)
						println("led on (blinking)")
						stateTimer = TimerActor("timer_blink_on", 
							scope, context!!, "local_tout_led_blink_on", 250.toLong() )
					}
					 transition(edgeName="t03",targetState="blink_off",cond=whenTimeout("local_tout_led_blink_on"))   
					transition(edgeName="t04",targetState="handle_update",cond=whenEvent("update_led"))
				}	 
				state("blink_off") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "led(blink_off,${newState})"  
						)
						println("led off (blinking)")
						stateTimer = TimerActor("timer_blink_off", 
							scope, context!!, "local_tout_led_blink_off", 250.toLong() )
					}
					 transition(edgeName="t05",targetState="blink_on",cond=whenTimeout("local_tout_led_blink_off"))   
					transition(edgeName="t06",targetState="handle_update",cond=whenEvent("update_led"))
				}	 
			}
		}
}
