/* Generated by AN DISI Unibo */ 
package it.unibo.ctxalarm
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.115", this, "demo0.pl", "sysRules.pl"
	)
}

