/* Generated by AN DISI Unibo */ 
package it.unibo.alarmcontrol

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Alarmcontrol ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var ISHOME: Boolean = true
			   val DLIMIT: Int = 10
			   var DISABLE: Boolean = false
			   
			   //define sonar
			   val simulate       = true
			   val sonarActorName = "alarmcontrol"
			   val usingDomain    = false
			
				
			   fun checkIsHome(F: String, T: String) : Boolean {
			       return F==T;
			   }	   
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("Activate the sonar")
						updateResourceRep( "alarmcontrol(activateSonar)"  
						)
						sonarConfig.configureTheSonar( simulate, sonarActorName, usingDomain  )
						if(   `it.unibo`.radarSystem22.domain.utils.DomainSystemConfig.simulation  
						 ){println("sonar simulator testing")
						forward("sonaractivate", "info(ok)" ,"sonarsimulatortesting" ) 
						}
						else
						 {println("sonar real")
						 forward("sonaractivate", "info(ok)" ,"sonardatasource" ) 
						 }
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("wait")
					}
					 transition(edgeName="t034",targetState="handle_moving",cond=whenEvent("moving"))
					transition(edgeName="t035",targetState="handle_distance",cond=whenEvent("sonardistance"))
				}	 
				state("handle_moving") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moving(F,T)"), Term.createTerm("moving(F,T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val F = payloadArg(0)    
								 val T = payloadArg(1)    
								 ISHOME=checkIsHome(F,T)  
								updateResourceRep( "alarmcontrol(handle_moving,${F},${T})"  
								)
								if(  ISHOME==true  
								 ){println("led off")
								}
								else
								 {println("led blink")
								 }
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("handle_distance") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(V)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val D = payloadArg(0).toInt()  
								if(  ISHOME==false && D<DLIMIT 
								 ){println("led on")
								}
								else
								 {println("led blink")
								 }
								if(  D<DLIMIT 
								 ){updateResourceRep( "alarmcontrol(handle_distance,${D},${DLIMIT},true)"  
								)
								updateResourceRep( "alarmcontrol(disable)"  
								)
								}
								else
								 {if(  D>=DLIMIT && DISABLE==true   
								  ){updateResourceRep( "alarmcontrol(handle_distance,${D},${DLIMIT},false)"  
								 )
								 updateResourceRep( "alarmcontrol(enable)"  
								 )
								 }
								 else
								  {updateResourceRep( "alarmcontrol(handle_distance,${D},${DLIMIT},${DISABLE})"  
								  )
								  }
								 }
								if(  D<DLIMIT 
								 ){ DISABLE=true  
								forward("disable", "disable(_)" ,"transporttrolley" ) 
								}
								if(  D>=DLIMIT && DISABLE==true   
								 ){ DISABLE=false  
								forward("enable", "enable(_)" ,"transporttrolley" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
