package alarmSonar.configureSonarSubsystem

import it.unibo.kactor.ActorBasic
import it.unibo.kactor.sysUtil

lateinit var firstActorInPipe : ActorBasic

fun configureTheSonar(simulate : Boolean=true, sonarActorName : String = "sonar"){
    createThePipe(simulate, sonarActorName)
}

fun createThePipe( simulate : Boolean, sonarActorName : String  ){
    if( simulate )  firstActorInPipe = sysUtil.getActor("sonarsimulator")!!  //generates simulated data
    else firstActorInPipe           = sysUtil.getActor("sonardatasource")!!  //generates REAL data
    firstActorInPipe.
        subscribeLocalActor("datacleaner"). 		//removes 'wrong' data''
        //subscribeLocalActor("datalogger").		    //logs (shows) the data generated by the sonar
        //subscribeLocalActor("sonar").				//handles sonarrobot but does not propagate ...
        //subscribeLocalActor("distancefilter").		//propagates the lcoal stream event obstacle
        subscribeLocalActor(sonarActorName)
}