/* Generated by AN DISI Unibo */ 
package it.unibo.led_alarm_control

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led_alarm_control ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CoapObserverSupport(myself, "127.0.0.1","8096","ctxrobot","basicrobotwrapper")
						CoapObserverSupport(myself, "127.0.0.1","8096","ctxrobot","mover")
						CoapObserverSupport(myself, "127.0.0.1","8096","ctxrobot","pickupdropouthandler")
					}
					 transition(edgeName="t065",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								emit("update_led", "update_led(_)" ) 
						}
					}
					 transition(edgeName="t066",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
			}
		}
}
