/* Generated by AN DISI Unibo */ 
package it.unibo.test_sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Test_sonar ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						emit("update_sonar", "update_sonar(8)" ) 
						delay(2000) 
						emit("update_sonar", "update_sonar(12)" ) 
						delay(2000) 
						emit("update_sonar", "update_sonar(7)" ) 
					}
				}	 
			}
		}
}
