/* Generated by AN DISI Unibo */ 
package it.unibo.ctxserver
import it.unibo.kactor.QakContext
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "demo0.pl", "sysRules.pl", "ctxserver"
	)
}

