/* Generated by AN DISI Unibo */ 
package it.unibo.ctxserver
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.138", this, "demo0.pl", "sysRules.pl"
	)
}

