/* Generated by AN DISI Unibo */ 
package it.unibo.testwasteservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Testwasteservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						request("depositrequest", "depositrequest(GLASS,11)" ,"wasteservice" )  
					}
					 transition(edgeName="t017",targetState="error",cond=whenReply("loadaccepted"))
					transition(edgeName="t018",targetState="s1",cond=whenReply("loadrejected"))
				}	 
				state("s1") { //this:State
					action { //it:State
						println("load rejected successfully")
						request("depositrequest", "depositrequest(PLASTIC,3)" ,"wasteservice" )  
					}
					 transition(edgeName="t019",targetState="s2",cond=whenReply("loadaccepted"))
					transition(edgeName="t020",targetState="error",cond=whenReply("loadrejected"))
				}	 
				state("s2") { //this:State
					action { //it:State
						println("load accepted successfully")
					}
				}	 
				state("error") { //this:State
					action { //it:State
						println("errore")
					}
				}	 
			}
		}
}
