/* Generated by AN DISI Unibo */ 
package it.unibo.alarmreceiverbasicrobot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Alarmreceiverbasicrobot ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("wait") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "alarmreceiverbasicrobot(wait)"  
						)
						if( checkMsgContent( Term.createTerm("disable(_)"), Term.createTerm("disable(BOOL)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0).toBoolean()  
								 ){forward("disable", "disable(_)" ,"basicrobotwrapper" ) 
								}
								else
								 {forward("enable", "enable(_)" ,"basicrobotwrapper" ) 
								 }
						}
					}
					 transition(edgeName="t029",targetState="wait",cond=whenEvent("disable"))
				}	 
			}
		}
}
