/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 lateinit var tmp : String  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						 sysUtil.logMsgs=true  
					}
					 transition(edgeName="t031",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("handle_cmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move(POSITION)"), Term.createTerm("move(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 tmp = payloadArg(0)  
								println("move(${tmp})")
								forward("noMsg", "noMsg(_)" ,"transporttrolley" ) 
						}
					}
					 transition(edgeName="toNewState32",targetState="moving_home",cond=whenDispatchGuarded("noMsg",{ tmp=="HOME"  
					}))
					transition(edgeName="toNewState33",targetState="moving_indoor",cond=whenDispatchGuarded("noMsg",{ tmp=="INDOOR"  
					}))
					transition(edgeName="toNewState34",targetState="moving_plasticbox",cond=whenDispatchGuarded("noMsg",{ tmp=="PLASTICBOX"  
					}))
					transition(edgeName="toNewState35",targetState="moving_glassbox",cond=whenDispatchGuarded("noMsg",{ tmp=="GLASSBOX"  
					}))
				}	 
				state("moving_home") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_home", 
							scope, context!!, "local_tout_transporttrolley_moving_home", 1000.toLong() )
					}
					 transition(edgeName="t036",targetState="moved_home",cond=whenTimeout("local_tout_transporttrolley_moving_home"))   
					transition(edgeName="t037",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_home") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached HOME")
					}
					 transition(edgeName="t038",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moving_indoor") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_indoor", 
							scope, context!!, "local_tout_transporttrolley_moving_indoor", 1000.toLong() )
					}
					 transition(edgeName="t039",targetState="moved_indoor",cond=whenTimeout("local_tout_transporttrolley_moving_indoor"))   
					transition(edgeName="t040",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_indoor") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached INDOOR")
					}
					 transition(edgeName="t041",targetState="handle_cmd",cond=whenRequest("move"))
					transition(edgeName="t042",targetState="pickUp",cond=whenRequest("pickup"))
				}	 
				state("moving_plasticbox") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_plasticbox", 
							scope, context!!, "local_tout_transporttrolley_moving_plasticbox", 1000.toLong() )
					}
					 transition(edgeName="t043",targetState="moved_plasticbox",cond=whenTimeout("local_tout_transporttrolley_moving_plasticbox"))   
					transition(edgeName="t044",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_plasticbox") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached PLASTICBOX")
					}
					 transition(edgeName="t045",targetState="handle_cmd",cond=whenRequest("move"))
					transition(edgeName="t046",targetState="dropOut",cond=whenRequest("dropout"))
				}	 
				state("moving_glassbox") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_glassbox", 
							scope, context!!, "local_tout_transporttrolley_moving_glassbox", 1000.toLong() )
					}
					 transition(edgeName="t047",targetState="moved_glassbox",cond=whenTimeout("local_tout_transporttrolley_moving_glassbox"))   
					transition(edgeName="t048",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_glassbox") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached GLASSBOX")
					}
					 transition(edgeName="t049",targetState="handle_cmd",cond=whenRequest("move"))
					transition(edgeName="t050",targetState="dropOut",cond=whenRequest("dropout"))
				}	 
				state("pickUp") { //this:State
					action { //it:State
						delay(1000) 
						answer("pickup", "pickupanswer", "pickupanswer(OK)"   )  
						println("robot pickedUp")
					}
					 transition(edgeName="t051",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("dropOut") { //this:State
					action { //it:State
						delay(1000) 
						answer("dropout", "dropoutanswer", "dropoutanswer(OK)"   )  
						println("robot droppedOut")
					}
					 transition(edgeName="t052",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
			}
		}
}
