/* Generated by AN DISI Unibo */ 
package it.unibo.pickupdropouthandler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Pickupdropouthandler ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("wait") { //this:State
					action { //it:State
						discardMessages = false
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(wait)"  
						)
					}
					 transition(edgeName="t020",targetState="do_dropout",cond=whenRequest("dropout"))
					transition(edgeName="t021",targetState="do_pickup",cond=whenRequest("pickup"))
					transition(edgeName="t022",targetState="alarm",cond=whenEvent("alarm"))
				}	 
				state("alarm") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(alarm)"  
						)
					}
					 transition(edgeName="t023",targetState="wait",cond=whenEvent("alarmceased"))
				}	 
				state("do_dropout") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(do_dropout)"  
						)
						stateTimer = TimerActor("timer_do_dropout", 
							scope, context!!, "local_tout_pickupdropouthandler_do_dropout", 1000.toLong() )
					}
					 transition(edgeName="t024",targetState="done_dropout",cond=whenTimeout("local_tout_pickupdropouthandler_do_dropout"))   
					transition(edgeName="t025",targetState="halt_dropout",cond=whenEvent("alarm"))
				}	 
				state("halt_dropout") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(halt_dropout)"  
						)
					}
					 transition(edgeName="t026",targetState="resume_dropout",cond=whenEvent("alarmceased"))
				}	 
				state("resume_dropout") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(resume_dropout)"  
						)
						stateTimer = TimerActor("timer_resume_dropout", 
							scope, context!!, "local_tout_pickupdropouthandler_resume_dropout", 1000.toLong() )
					}
					 transition(edgeName="t027",targetState="done_dropout",cond=whenTimeout("local_tout_pickupdropouthandler_resume_dropout"))   
				}	 
				state("done_dropout") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(done_dropout)"  
						)
						answer("dropout", "dropoutanswer", "dropoutanswer(OK)"   )  
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("do_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(do_pickup)"  
						)
						stateTimer = TimerActor("timer_do_pickup", 
							scope, context!!, "local_tout_pickupdropouthandler_do_pickup", 1000.toLong() )
					}
					 transition(edgeName="t028",targetState="done_pickup",cond=whenTimeout("local_tout_pickupdropouthandler_do_pickup"))   
					transition(edgeName="t029",targetState="halt_pickup",cond=whenEvent("alarm"))
				}	 
				state("halt_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(halt_pickup)"  
						)
					}
					 transition(edgeName="t030",targetState="resume_pickup",cond=whenEvent("alarmceased"))
				}	 
				state("resume_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(resume_pickup)"  
						)
						stateTimer = TimerActor("timer_resume_pickup", 
							scope, context!!, "local_tout_pickupdropouthandler_resume_pickup", 1000.toLong() )
					}
					 transition(edgeName="t031",targetState="done_pickup",cond=whenTimeout("local_tout_pickupdropouthandler_resume_pickup"))   
				}	 
				state("done_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(done_pickup)"  
						)
						answer("pickup", "pickupanswer", "pickupanswer(OK)"   )  
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
