/* Generated by AN DISI Unibo */ 
package it.unibo.ctxservertest
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "demowasteservice.pl", "sysRules.pl","ctxservertest"
	)
}

