/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 lateinit var tmp : String  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						println("$name in ${currentState.stateName} | $currentMsg")
						 sysUtil.logMsgs=true  
					}
					 transition(edgeName="t00",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("handle_cmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move(POSITION)"), Term.createTerm("move(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 tmp = payloadArg(0)  
								println("move(${tmp})")
								forward("noMsg", "noMsg(_)" ,"transporttrolley" ) 
						}
					}
					 transition(edgeName="toNewState1",targetState="moving_home",cond=whenDispatchGuarded("noMsg",{ tmp=="HOME"  
					}))
					transition(edgeName="toNewState2",targetState="moving_indoor",cond=whenDispatchGuarded("noMsg",{ tmp=="INDOOR"  
					}))
					transition(edgeName="toNewState3",targetState="moving_plasticbox",cond=whenDispatchGuarded("noMsg",{ tmp=="PLASTICBOX"  
					}))
					transition(edgeName="toNewState4",targetState="moving_glassbox",cond=whenDispatchGuarded("noMsg",{ tmp=="GLASSBOX"  
					}))
				}	 
				state("moving_home") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_home", 
							scope, context!!, "local_tout_transporttrolley_moving_home", 1000.toLong() )
					}
					 transition(edgeName="t05",targetState="moved_home",cond=whenTimeout("local_tout_transporttrolley_moving_home"))   
					transition(edgeName="t06",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_home") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached HOME")
					}
					 transition(edgeName="t07",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moving_indoor") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_indoor", 
							scope, context!!, "local_tout_transporttrolley_moving_indoor", 1000.toLong() )
					}
					 transition(edgeName="t08",targetState="moved_indoor",cond=whenTimeout("local_tout_transporttrolley_moving_indoor"))   
					transition(edgeName="t09",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_indoor") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached INDOOR")
					}
					 transition(edgeName="t010",targetState="handle_cmd",cond=whenRequest("move"))
					transition(edgeName="t011",targetState="pickUp",cond=whenRequest("pickup"))
				}	 
				state("moving_plasticbox") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_plasticbox", 
							scope, context!!, "local_tout_transporttrolley_moving_plasticbox", 1000.toLong() )
					}
					 transition(edgeName="t012",targetState="moved_plasticbox",cond=whenTimeout("local_tout_transporttrolley_moving_plasticbox"))   
					transition(edgeName="t013",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_plasticbox") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached PLASTICBOX")
					}
					 transition(edgeName="t014",targetState="handle_cmd",cond=whenRequest("move"))
					transition(edgeName="t015",targetState="dropOut",cond=whenRequest("dropout"))
				}	 
				state("moving_glassbox") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_moving_glassbox", 
							scope, context!!, "local_tout_transporttrolley_moving_glassbox", 1000.toLong() )
					}
					 transition(edgeName="t016",targetState="moved_glassbox",cond=whenTimeout("local_tout_transporttrolley_moving_glassbox"))   
					transition(edgeName="t017",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("moved_glassbox") { //this:State
					action { //it:State
						answer("move", "moveanswer", "moveanswer(OK)"   )  
						println("robot reached GLASSBOX")
					}
					 transition(edgeName="t018",targetState="handle_cmd",cond=whenRequest("move"))
					transition(edgeName="t019",targetState="dropOut",cond=whenRequest("dropout"))
				}	 
				state("pickUp") { //this:State
					action { //it:State
						delay(1000) 
						answer("pickup", "pickupanswer", "pickupanswer(OK)"   )  
						println("robot pickedUp")
					}
					 transition(edgeName="t020",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
				state("dropOut") { //this:State
					action { //it:State
						delay(1000) 
						answer("dropout", "dropoutanswer", "dropoutanswer(OK)"   )  
						println("robot droppedOut")
					}
					 transition(edgeName="t021",targetState="handle_cmd",cond=whenRequest("move"))
				}	 
			}
		}
}
