/* Generated by AN DISI Unibo */ 
package it.unibo.pickupdropouthandler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Pickupdropouthandler ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("handle_prio") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(handle_prio)"  
						)
						stateTimer = TimerActor("timer_handle_prio", 
							scope, context!!, "local_tout_pickupdropouthandler_handle_prio", 10.toLong() )
					}
					 transition(edgeName="t020",targetState="wait",cond=whenTimeout("local_tout_pickupdropouthandler_handle_prio"))   
					transition(edgeName="t021",targetState="halt",cond=whenDispatch("disable"))
				}	 
				state("halt") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(halt)"  
						)
					}
					 transition(edgeName="t022",targetState="handle_prio",cond=whenDispatch("enable"))
				}	 
				state("wait") { //this:State
					action { //it:State
						discardMessages = false
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(wait)"  
						)
					}
					 transition(edgeName="t023",targetState="halt",cond=whenDispatch("disable"))
					transition(edgeName="t024",targetState="do_dropout",cond=whenRequest("dropout"))
					transition(edgeName="t025",targetState="do_pickup",cond=whenRequest("pickup"))
				}	 
				state("do_dropout") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(do_dropout)"  
						)
						println("pickupdropouthandler | DROPOUT STARTING...")
						delay(1000) 
						println("pickupdropouthandler | DROPOUT COMPLETE")
						answer("dropout", "dropoutanswer", "dropoutanswer(OK)"   )  
					}
					 transition( edgeName="goto",targetState="handle_prio", cond=doswitch() )
				}	 
				state("do_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "pickupdropouthandler(do_pickup)"  
						)
						println("pickupdropouthandler | PICKUP STARTING...")
						delay(1000) 
						println("pickupdropouthandler | PICKUP COMPLETE")
						answer("pickup", "pickupanswer", "pickupanswer(OK)"   )  
					}
					 transition( edgeName="goto",targetState="handle_prio", cond=doswitch() )
				}	 
			}
		}
}
