/* Generated by AN DISI Unibo */ 
package it.unibo.commandissuerfortests

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Commandissuerfortests ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				lateinit var RES : String
		return { //this:ActionBasciFsm
				state("wait") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						discardMessages = false
						updateResourceRep( "commandissuerfortests(wait)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="toNewState89",targetState="req_pickup",cond=whenRequest("pickup"))
					transition(edgeName="toNewState90",targetState="req_dropout",cond=whenRequest("dropout"))
					transition(edgeName="toNewState91",targetState="req_cmdsync",cond=whenRequest("cmdsync"))
				}	 
				state("req_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "commandissuerfortests(req_pickup)"  
						)
						request("pickup", "pickup(_)" ,"pickupdropouthandler" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="toNewState92",targetState="chk_pickup",cond=whenReply("pickupanswer"))
				}	 
				state("chk_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "commandissuerfortests(chk_pickup)"  
						)
						if( checkMsgContent( Term.createTerm("pickupanswer(RESULT)"), Term.createTerm("pickupanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
								if(  RES=="OK"  
								 ){answer("pickup", "pickupanswer", "pickupanswer(OK)"   )  
								}
								else
								 {answer("pickup", "pickupanswer", "pickupanswer(ERROR)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("req_dropout") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "commandissuerfortests(req_dropout)"  
						)
						request("dropout", "dropout(_)" ,"pickupdropouthandler" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="toNewState93",targetState="chk_dropout",cond=whenReply("dropoutanswer"))
				}	 
				state("chk_dropout") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "commandissuerfortests(chk_dropout)"  
						)
						if( checkMsgContent( Term.createTerm("dropoutanswer(RESULT)"), Term.createTerm("dropoutanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
								if(  RES=="OK"  
								 ){answer("dropout", "dropoutanswer", "dropoutanswer(OK)"   )  
								}
								else
								 {answer("dropout", "dropoutanswer", "dropoutanswer(ERROR)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("req_cmdsync") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						 var Move : ws.Move? = null  
						if( checkMsgContent( Term.createTerm("cmdsync(MOVE)"), Term.createTerm("cmdsync(MOVE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Move=ws.Move.valueOf(payloadArg(0))  
								request("cmdsync", "cmdsync($Move)" ,"basicrobotwrapper" )  
						}
						updateResourceRep( "commandissuerfortests(req_cmdsync,$Move)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="toNewState94",targetState="chk_cmdsync",cond=whenReply("cmdanswer"))
				}	 
				state("chk_cmdsync") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "commandissuerfortests(chk_cmdsync)"  
						)
						if( checkMsgContent( Term.createTerm("cmdanswer(RESULT)"), Term.createTerm("cmdanswer(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RES = payloadArg(0) 
								if(  RES=="OK"  
								 ){answer("cmdsync", "cmdanswer", "cmdanswer(OK)"   )  
								}
								else
								 {answer("cmdsync", "cmdanswer", "cmdanswer(ERROR)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
